# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Uno más de la tribu
email: quinteroac@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Página personal de Victor Quintero
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://quinteroac.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: quinteroac
github_username:  quinteroac

#  Bienvenido, éste es mi espacio personal donde podrás conocer un poco acerca de mi. Mis gustos y aficiones
#  tanto en lo personal como en lo profesional. También me gusta escribir acerca de ellos.
  #Nací en Guadalajara, Jalisco en México y aquí llevo radicando toda mi vida, estudie Ingeniería en Comunicaciones y Electronica pero
  #los vientos me llevaron a los caminos del desarrollo de software, analisis de negocio y dirección de proyectos.
  #Me interesan mucho temas como el liderazgo tribal, metodologías agiles y el entorno de tecnologías que se han
  #desarrollado a partir de las plataformas web y moviles que han ido surgiendo.
  #También me gusta la musica, convivir con los amigos y de vez en cuando los videojuegos. Me gusta la historia de la humanidad,
  #en especial la historia antigua, Romanos, Griegos, Egipcios y así.
  #Tengo una hija y ella es mi vida.


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
