name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install TypeScript
      run: npm install -g typescript --legacy-peer-deps

    - name: Install Dependencies
      run: |
        npm install --legacy-peer-deps
        npm install -D webpack-cli --legacy-peer-deps
        npm audit fix --legacy-peer-deps

    - name: Build
      run: npx webpack
